apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: default
data:
  config.toml: |
    concurrent = 2

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://git.fanbuy/"
      token = "LzSZjTj39z3ozF9Lxzxu"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "default"
        image = "busybox"
