apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: default
data:
  config.toml: |
    concurrent = 2

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://git.fanbuy/"
      token = "zxBBzS4DP5siyLyEJLAy"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "default"
        image = "maven:3-jdk-8"
