apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanbuy-ingress
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/proxy-body-size: "1024M"
spec:
  rules:
  - host: jenkins.fanbuy
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
        path: /
