apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanbuy-ingress
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/proxy-body-size: "1024M"
spec:
  rules:
  - host: git.fanbuy
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab-ce-gitlab-ce 
          servicePort: 80
